// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: simple.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SimpleClient is the client API for Simple service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimpleClient interface {
	GetMessage(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Message, error)
	PutMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Name, error)
	PingPong(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	ListMessage(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Simple_ListMessageClient, error)
}

type simpleClient struct {
	cc grpc.ClientConnInterface
}

func NewSimpleClient(cc grpc.ClientConnInterface) SimpleClient {
	return &simpleClient{cc}
}

func (c *simpleClient) GetMessage(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/simple.Simple/GetMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simpleClient) PutMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Name, error) {
	out := new(Name)
	err := c.cc.Invoke(ctx, "/simple.Simple/PutMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simpleClient) PingPong(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/simple.Simple/PingPong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simpleClient) ListMessage(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Simple_ListMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &Simple_ServiceDesc.Streams[0], "/simple.Simple/ListMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &simpleListMessageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Simple_ListMessageClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type simpleListMessageClient struct {
	grpc.ClientStream
}

func (x *simpleListMessageClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SimpleServer is the server API for Simple service.
// All implementations should embed UnimplementedSimpleServer
// for forward compatibility
type SimpleServer interface {
	GetMessage(context.Context, *Name) (*Message, error)
	PutMessage(context.Context, *Message) (*Name, error)
	PingPong(context.Context, *Message) (*Message, error)
	ListMessage(*emptypb.Empty, Simple_ListMessageServer) error
}

// UnimplementedSimpleServer should be embedded to have forward compatible implementations.
type UnimplementedSimpleServer struct {
}

func (UnimplementedSimpleServer) GetMessage(context.Context, *Name) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessage not implemented")
}
func (UnimplementedSimpleServer) PutMessage(context.Context, *Message) (*Name, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutMessage not implemented")
}
func (UnimplementedSimpleServer) PingPong(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingPong not implemented")
}
func (UnimplementedSimpleServer) ListMessage(*emptypb.Empty, Simple_ListMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method ListMessage not implemented")
}

// UnsafeSimpleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimpleServer will
// result in compilation errors.
type UnsafeSimpleServer interface {
	mustEmbedUnimplementedSimpleServer()
}

func RegisterSimpleServer(s grpc.ServiceRegistrar, srv SimpleServer) {
	s.RegisterService(&Simple_ServiceDesc, srv)
}

func _Simple_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simple.Simple/GetMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleServer).GetMessage(ctx, req.(*Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simple_PutMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleServer).PutMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simple.Simple/PutMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleServer).PutMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simple_PingPong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleServer).PingPong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simple.Simple/PingPong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleServer).PingPong(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Simple_ListMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SimpleServer).ListMessage(m, &simpleListMessageServer{stream})
}

type Simple_ListMessageServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type simpleListMessageServer struct {
	grpc.ServerStream
}

func (x *simpleListMessageServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

// Simple_ServiceDesc is the grpc.ServiceDesc for Simple service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Simple_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "simple.Simple",
	HandlerType: (*SimpleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessage",
			Handler:    _Simple_GetMessage_Handler,
		},
		{
			MethodName: "PutMessage",
			Handler:    _Simple_PutMessage_Handler,
		},
		{
			MethodName: "PingPong",
			Handler:    _Simple_PingPong_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListMessage",
			Handler:       _Simple_ListMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "simple.proto",
}
